- Media:
    - Jellyfin:
        icon: jellyfin.png
        href: http://jellyfin.${DOMAIN:-localhost}
        description: Media Server
        widget:
          type: jellyfin
          url: http://jellyfin:8096
          key: ${HOMEPAGE_VAR_JELLYFIN_API_KEY}

- Requests:
    - Seerr:
        icon: overseerr.png
        href: http://seerr.${DOMAIN:-localhost}
        description: Media Requests
        widget:
          type: overseerr
          url: http://seerr:5055
          key: ${HOMEPAGE_VAR_SEERR_API_KEY}

- Movies & TV:
    - Radarr:
        icon: radarr.png
        href: http://radarr.${DOMAIN:-localhost}
        description: Movie Management
        widget:
          type: radarr
          url: http://radarr:7878
          key: ${HOMEPAGE_VAR_RADARR_API_KEY}

    - Sonarr:
        icon: sonarr.png
        href: http://sonarr.${DOMAIN:-localhost}
        description: TV Series Management
        widget:
          type: sonarr
          url: http://sonarr:8989
          key: ${HOMEPAGE_VAR_SONARR_API_KEY}

    - Bazarr:
        icon: bazarr.png
        href: http://bazarr.${DOMAIN:-localhost}
        description: Subtitles Management
        widget:
          type: bazarr
          url: http://bazarr:6767
          key: ${HOMEPAGE_VAR_BAZARR_API_KEY}

- Indexers:
    - Prowlarr:
        icon: prowlarr.png
        href: http://prowlarr.${DOMAIN:-localhost}
        description: Indexer Manager
        widget:
          type: prowlarr
          url: http://prowlarr:9696
          key: ${HOMEPAGE_VAR_PROWLARR_API_KEY}

    - Jackett:
        icon: jackett.png
        href: http://jackett.${DOMAIN:-localhost}
        description: Indexer Proxy
        widget:
          type: jackett
          url: http://jackett:9117
          key: ${HOMEPAGE_VAR_JACKETT_API_KEY}

- Downloads:
    - qBittorrent:
        icon: qbittorrent.png
        href: http://qbittorrent.${DOMAIN:-localhost}
        description: Torrent Client
        widget:
          type: qbittorrent
          url: http://qbittorrent:8080
          username: admin
          password: adminadmin

- Monitoring:
    - Jellystat:
        icon: jellystat.png
        href: http://jellystat.${DOMAIN:-localhost}
        description: Jellyfin Statistics
        widget:
          type: jellystat
          url: http://jellystat:3000
          key: ${HOMEPAGE_VAR_JELLYSTAT_API_KEY}

    - What's Up Docker:
        icon: whatsupdocker.png
        href: http://wud.${DOMAIN:-localhost}
        description: Container Updates
        widget:
          type: whatsupdocker
          url: http://wud:3000

- Infrastructure:
    - Traefik:
        icon: traefik.png
        href: http://traefik.${DOMAIN:-localhost}
        description: Reverse Proxy
        widget:
          type: traefik
          url: http://traefik:8080

    - Dockhand:
        icon: dockhand.png
        href: http://dockhand.${DOMAIN:-localhost}
        description: Container Management

- Dashboards:
    - Homarr:
        icon: homarr.png
        href: http://homarr.${DOMAIN:-localhost}
        description: Alternative Dashboard

- Tools:
    - Flaresolverr:
        icon: flaresolverr.png
        href: http://flaresolverr.${DOMAIN:-localhost}
        description: Cloudflare Solver

    - Huntarr:
        icon: huntarr.png
        href: http://huntarr.${DOMAIN:-localhost}
        description: Media Hunting

    - Recommendarr:
        icon: recommendarr.png
        href: http://recommendarr.${DOMAIN:-localhost}
        description: Media Recommendations

    - Deleterr:
        icon: deleterr.png
        href: http://deleterr.${DOMAIN:-localhost}
        description: Media Cleanup
